---
PRINT_ALPACA: false
EMAIL_REPORTER: false
APPLY_FIXES: all

# Lint specifig settings
ENABLE: [MARKDOWN, YAML, COPYPASTE, CREDENTIALS]

COPYPASTE_JSCPD_ARGUMENTS: --ignore "test/lib,report,LICENSES"
